name: route_e_commerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.5
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  # meta: ^1.11.0
  readmore: ^2.2.0
  smooth_page_indicator: ^1.1.0
flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/images/splash_screen.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
    - assets/images/announcements/
    - assets/images/announcements/2.0x/
    - assets/images/announcements/3.0x/
    - assets/images/categories/
    - assets/images/categories/2.0x/
    - assets/images/categories/3.0x/
    - assets/images/items/
    - assets/images/items/2.0x/
    - assets/images/items/3.0x/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
